export const devotionalStudy = {
  title: 'ORDEN FINANCIERO A LA MANERA DE DIOS',
  sections: [
    {
      title: '1. Mayordomos y administradores de Dios',
      content: [
        { type: 'text', value: '1. Todo pertenece a Dios; Él es el ' },
        { type: 'blank', id: '1-1', answer: 'creador' },
        { type: 'text', value: ' y ' },
        { type: 'blank', id: '1-2', answer: 'dueño' },
        { type: 'text', value: ' de todo.' },
        { type: 'text', value: '\n2. Todo lo que tengo es por la ' },
        { type: 'blank', id: '1-3', answer: 'bondad' },
        { type: 'text', value: ' de Dios.' },
        { type: 'text', value: '\n3. Lo que Dios me da es para que yo lo ' },
        { type: 'blank', id: '1-4', answer: 'administre' },
        { type: 'text', value: ' correctamente.' },
        { type: 'text', value: '\n4. El administrador reconoce que todo lo que tiene proviene de Dios. Gestionamos y administramos la propiedad y las ' },
        { type: 'blank', id: '1-5', answer: 'pertenencias' },
        { type: 'text', value: ' de Dios.' },
      ],
    },
    {
      title: '2. Causas del desorden económico',
      content: [
        { type: 'text', value: '1. ' },
        { type: 'blank', id: '2-1', answer: 'Argumentos' },
        { type: 'text', value: ' basados en malas experiencias o en lo que has oído a otros (mentiras).' },
        { type: 'text', value: '\n2. La ' },
        { type: 'blank', id: '2-2', answer: 'tacañería' },
        { type: 'text', value: '. Querer satisfacer solo las propias necesidades (egoísmo).' },
        { type: 'text', value: '\n3. ' },
        { type: 'blank', id: '2-3', answer: 'Avaricia' },
        { type: 'text', value: '. Quieres más de lo que necesitas; nunca es suficiente (codicia).' },
        { type: 'text', value: '\n4. Falta de ' },
        { type: 'blank', id: '2-4', answer: 'conocimiento' },
        { type: 'text', value: '. No tienes suficiente conocimiento sobre el orden de Dios en la economía (temor). Vives bajo una maldición económica.' },
      ],
    },
    {
      title: '3. El sistema económico de Dios',
      content: [
        { type: 'text', value: '1. ' },
        { type: 'blank', id: '3-1', answer: 'Ofrenda' },
        { type: 'text', value: '. Donativo voluntario que expresa gratitud y demuestra amor.' },
        { type: 'text', value: '\n2. ' },
        { type: 'blank', id: '3-2', answer: 'Diezmo' },
        { type: 'text', value: '. Una parte determinada que pone a prueba nuestra obediencia y temor a Dios.' },
        { type: 'text', value: '\n3. ' },
        { type: 'blank', id: '3-3', answer: 'Primicia' },
        { type: 'text', value: '. Es un regalo escogido que hace eco en el tiempo venidero. Puede ser lo primero o lo último que te quede.' },
      ],
    },
    {
      title: '4. Consejos prácticos',
      content: [
        { type: 'text', value: '1. Da siempre ' },
        { type: 'blank', id: '4-1', answer: 'primero' },
        { type: 'text', value: ' a Dios. Este es el orden en que Dios bendice.' },
        { type: 'text', value: '\n2. Haz un ' },
        { type: 'blank', id: '4-2', answer: 'presupuesto' },
        { type: 'text', value: '. No vivas por encima de tus posibilidades; calcula bien tus gastos.' },
        { type: 'text', value: '\n3. Establece ' },
        { type: 'blank', id: '4-3', answer: 'metas' },
        { type: 'text', value: ' financieras. ¿Cuánto deberías ahorrar? ¿Para qué debes ahorrar?' },
        { type: 'text', value: '\n4. ' },
        { type: 'blank', id: '4-4', answer: 'Planifica' },
        { type: 'text', value: ' tus ofrendas. Divide la dádiva para todo el mes.' },
      ],
    },
  ],
};